SELECT C.CAR_ID, C.CAR_TYPE,
    ROUND(C.DAILY_FEE*((1-(P.DISCOUNT_RATE*0.01))*30)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
ON P.CAR_TYPE = C.CAR_TYPE AND P.DURATION_TYPE = '30일 이상'
WHERE C.CAR_TYPE IN ('세단', 'SUV') 
AND C.CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    WHERE START_DATE <= '2022-11-30'
        AND END_DATE >= '2022-11-01'
)
AND ROUND(C.DAILY_FEE*((1-(P.DISCOUNT_RATE*0.01))*30)) BETWEEN 500000 AND 1999999
ORDER BY FEE DESC, C.CAR_TYPE, C.CAR_ID DESC;