SELECT R1.FOOD_TYPE, R1.REST_ID, R1.REST_NAME, R2.FAVORITES
FROM REST_INFO R1
JOIN(
    SELECT I.FOOD_TYPE, MAX(I.FAVORITES) AS FAVORITES
    FROM REST_INFO I 
    GROUP BY FOOD_TYPE
) R2
ON R1.FOOD_TYPE = R2.FOOD_TYPE AND R1.FAVORITES = R2.FAVORITES
ORDER BY R1.FOOD_TYPE DESC;

