SELECT YEAR(S.SALES_DATE) AS YEAR, MONTH(S.SALES_DATE) AS MONTH, U.GENDER,  COUNT(DISTINCT U.USER_ID) AS USERS
FROM USER_INFO AS U
JOIN ONLINE_SALE S ON S.USER_ID = U.USER_ID
GROUP BY YEAR(S.SALES_DATE), MONTH(S.SALES_DATE), U.GENDER
HAVING U.GENDER IS NOT NULL
ORDER BY YEAR(S.SALES_DATE), MONTH(S.SALES_DATE), U.GENDER; 