SELECT COUNT(FNI.FISH_NAME) AS FISH_COUNT, FNI.FISH_NAME AS FISH_NAME
FROM FISH_NAME_INFO FNI
JOIN FISH_INFO FI ON FI.FISH_TYPE = FNI.FISH_TYPE
GROUP BY FNI.FISH_NAME
ORDER BY COUNT(FNI.FISH_NAME) DESC;