# 2021년에 가입한 사람
WITH JOIN_2021 AS (
    SELECT USER_ID
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
)

# 연,월 별로 상품을 구매한 사람 수, 가입한 전체 회원 수(이미 구함)
# 주문한 사람 중복 제거 필요
SELECT YEAR(O.SALES_DATE) AS YEAR, MONTH(O.SALES_DATE) AS MONTH, COUNT(DISTINCT O.USER_ID) AS PURCHASED_USERS, 
ROUND((COUNT(DISTINCT O.USER_ID) / (SELECT COUNT(*) FROM JOIN_2021)),1) AS PUCHASED_RATIO
FROM ONLINE_SALE O
JOIN JOIN_2021 J
ON J.USER_ID = O.USER_ID
GROUP BY YEAR(O.SALES_DATE), MONTH(O.SALES_DATE)
ORDER BY YEAR(O.SALES_DATE), MONTH(O.SALES_DATE);
