WITH RECURSIVE ECOLI_TREE AS(
    #1세대
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    #N세대
    SELECT C.ID, C.PARENT_ID, P.GENERATION + 1
    FROM ECOLI_DATA C
    JOIN ECOLI_TREE P
    ON C.PARENT_ID = P.ID
)

# PARENT_ID에 나타나지 않은 ID 구하기
SELECT COUNT(T.ID) AS `COUNT`, T.GENERATION AS GENERATION
FROM ECOLI_DATA D
JOIN ECOLI_TREE T
ON T.ID = D.ID
WHERE D.ID NOT IN (
    SELECT DISTINCT PARENT_ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NOT NULL
)
GROUP BY T.GENERATION
ORDER BY T.GENERATION;

