WITH AMOUNT_ORDERS AS (
    SELECT PRODUCT_ID, SUM(AMOUNT) AS AMOUNT_ORDER
    FROM FOOD_ORDER
    WHERE PRODUCE_DATE BETWEEN '2022-05-01' AND '2022-05-31'
    GROUP BY PRODUCT_ID
)

SELECT P.PRODUCT_ID, P.PRODUCT_NAME, A.AMOUNT_ORDER * P.PRICE AS TOTAL_SALES
FROM FOOD_PRODUCT P
JOIN AMOUNT_ORDERS A
ON A.PRODUCT_ID = P.PRODUCT_ID
ORDER BY A.AMOUNT_ORDER * P.PRICE DESC, P.PRODUCT_ID;