WITH JULY_SUMS AS (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS JULY_SUM
    FROM JULY
    GROUP BY FLAVOR
)

SELECT F.FLAVOR
FROM FIRST_HALF F
JOIN JULY_SUMS J
ON F.FLAVOR = J.FLAVOR
ORDER BY (F.TOTAL_ORDER + J.JULY_SUM) DESC
LIMIT 3;