WITH COUNT_REVIEWS AS (
    SELECT R.MEMBER_ID, P.MEMBER_NAME, COUNT(R.MEMBER_ID) AS COUNT_REVIEW
    FROM REST_REVIEW R
    JOIN MEMBER_PROFILE P
    ON P.MEMBER_ID = R.MEMBER_ID
    GROUP BY R.MEMBER_ID
),
FIND_MAX_REVIEWER_LIST AS (
    SELECT MEMBER_ID, MEMBER_NAME
    FROM COUNT_REVIEWS
    WHERE COUNT_REVIEW = (SELECT MAX(COUNT_REVIEW) FROM COUNT_REVIEWS)
)

SELECT MR.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE , '%Y-%m-%d') AS REVIEW_DATE
FROM FIND_MAX_REVIEWER_LIST MR
JOIN REST_REVIEW R
ON R.MEMBER_ID = MR.MEMBER_ID
ORDER BY DATE_FORMAT(R.REVIEW_DATE , '%Y-%m-%d'), R.REVIEW_TEXT;



