SELECT FI.ID AS ID, FNI.FISH_NAME AS FISH_NAME, FI.LENGTH
FROM FISH_INFO AS FI
JOIN FISH_NAME_INFO AS FNI ON FI.FISH_TYPE = FNI.FISH_TYPE
WHERE FI.LENGTH IN (
    SELECT MAX(F.LENGTH)    
    FROM FISH_INFO AS F
    WHERE F.FISH_TYPE = FI.FISH_TYPE
)
ORDER BY FI.ID