WITH SUM_SCORE AS (
    SELECT EMP_NO, SUM(SCORE) AS EMP_SCORE
    FROM HR_GRADE 
    GROUP BY EMP_NO
),
MAX_SCORE AS (
    SELECT MAX(EMP_SCORE) AS TOP
    FROM SUM_SCORE
)

SELECT S.EMP_SCORE AS SCORE, E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM SUM_SCORE S
JOIN HR_EMPLOYEES E ON S.EMP_NO = E.EMP_NO
JOIN MAX_SCORE M ON M.TOP = S.EMP_SCORE;