SELECT CONCAT_WS('/', '/home/grep/src', F.BOARD_ID, CONCAT(CONCAT(FILE_ID,FILE_NAME),FILE_EXT)) AS FILE_PATH
FROM USED_GOODS_FILE F
JOIN (
    SELECT BOARD_ID 
    FROM USED_GOODS_BOARD B
    WHERE B.VIEWS = (SELECT MAX(B1.VIEWS) FROM USED_GOODS_BOARD B1)
) B
ON B.BOARD_ID = F.BOARD_ID
ORDER BY F.FILE_ID DESC;
