WITH MAX_CATEGORY AS (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT P2
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY
)

SELECT P1.CATEGORY, M.MAX_PRICE, P1.PRODUCT_NAME
FROM FOOD_PRODUCT P1
JOIN MAX_CATEGORY M ON P1.PRICE = M.MAX_PRICE
AND P1.CATEGORY = M.CATEGORY
ORDER BY P1.PRICE DESC;
